AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'Guardfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/AsciiComments:
  AllowedChars: ['à', 'é', 'è', 'ë', 'ê', 'î', 'ï', 'ô', 'ù', 'ç', 'À', 'É', 'È', 'Ë', 'Ê', 'Î', 'Ï', 'Ô', 'Ù', 'Ç']

Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Layout/LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
